### ISSUE TITLE
Post-experiment rule status on dashboard 

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/educational-experiment-service#106]
The post-experiment rule status in the dashboard doesn't provide enough detail. If you select, for instance, Assign-Default, the dashboard only says the rule is Assign. It needs to display information from both dropdown fields to be useful.

**Comment by ppratikcr7** [comment]
Code is now fixed for this issue.

**Comment by ppratikcr7** [comment]
@amurphy-cl fix is merged, please verify
