### ISSUE TITLE
"Mean" vs "Average" in UI

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/educational-experiment-service#111]
We need to consistently use the term Mean for such measures in the monitor and UI, not a mix of Average and Mean.

**Comment by ppratikcr7** [comment]
Code is now fixed for this issue.

**Comment by amurphy-cl** [comment]
@ppratikcr7 feel free to assign issues to me to verify when fixed. Thanks!

**Comment by ppratikcr7** [comment]
@amurphy-cl fix is merged, please verify
