### ISSUE TITLE
Error/Audit log records

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/educational-experiment-service#115]
Records in the Error and Audit logs in UpGrade don't go back as far as we'd like. We should decide on how many records the log will show so that it's most useful.

**Comment by JD2455** [comment]
@amurphy-cl , @msandbothe  The reason for this is, There is a cloudwatch event rule which runs at every 12 hours and executes the lambda function with the input as 
`{
    "url": "{backendHostURL}/api/scheduledJobs/clearLogs",
    "body": {
        "logTypes": [
            "audit-logs",
            "error-logs"
        ]
    }
}`
Lambda function calls the API given in the input with the event body passed from the event rule. This API keeps only latest 25 logs from Error and Audit logs.
Code Ref - [Link](https://github.com/CarnegieLearningWeb/educational-experiment-service/blob/master/packages/Upgrade/src/api/services/ScheduledJobService.ts#L168)

Increasing value of offset [here](https://github.com/CarnegieLearningWeb/educational-experiment-service/blob/master/packages/Upgrade/src/api/services/ScheduledJobService.ts#L168) from 25 to some number will resolve this.

**Comment by JD2455** [comment]
@amurphy-cl Increased records of Error and Audit logs from 25 to 500.
Changes related to this issue is merged and hence closing this issue.
