### ISSUE TITLE
Remove unique identifier columns from UpGrade UI

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/educational-experiment-service#125]
We probably don't need to display the unique identifiers in the UI, so let's remove them 

Currently there is a column for unique identifier under Experiment Conditions, and another under Experiment Sites

**Comment by ppratikcr7** [comment]
@amurphy-cl It is fixed now. Please check.

**Comment by amurphy-cl** [comment]
Looks good!
