### ISSUE TITLE
Seeing a version bump in an incorrect order in the backend 1.0.23 release

### ISSUE THREAD

**Issue by nirmalpatel** [CarnegieLearningWeb/educational-experiment-service#127]
When I read the commit log for the backend 1.0.23 release, I see this sequence:

1.0.21, then
1.0.8, then  **<--- this looks like a problem to me**
1.0.22, then
1.023

You can see this sequence from the bottom of the log to the top of the log here: https://github.com/CarnegieLearningWeb/educational-experiment-service/releases/tag/upgrade-backend-v1.0.23

I'm not sure whether this is a harmful behavior or not, but reporting this as an issue as I found it odd.

**Comment by jerith666** [comment]
You're talking about these commits?

89fdce5 ci: version bump to v1.0.22
be1e8cc ci: version bump to v1.0.8
a6f5bfb ci: version bump to v1.0.21

They're touching different files (`packages/Upgrade` vs. `packages/Scheduler`), so I think this is okay.  cc @mfugate1.

```
$ git log -3 --oneline 89fdce5e --name-status -- '**/package*.json'
89fdce5e (tag: upgrade-backend-v1.0.22) ci: version bump to v1.0.22
M    packages/Upgrade/package-lock.json
M    packages/Upgrade/package.json
be1e8ccb (tag: upgrade-lambda-v1.0.8) ci: version bump to v1.0.8
M    packages/Schedular/package-lock.json
M    packages/Schedular/package.json
a6f5bfb2 (tag: upgrade-backend-v1.0.21) ci: version bump to v1.0.21
M    packages/Upgrade/package-lock.json
M    packages/Upgrade/package.json
```

**Comment by mfugate1** [comment]
Yeah, you've got three separately versioned artifacts in the same repo (frontend, backend, lambda). The changelog just does a diff between last commit and current.

Edit: Oh, I didn't even notice this was in the old repo. Yeah even in this case the backend and lambda artifacts were versioned separately

**Comment by nirmalpatel** [comment]
Got it @mfugate1 @jerith666, closing this, thanks!
