### ISSUE TITLE
Add support for alternative user IDs

### ISSUE THREAD

**Issue by jerith666** [CarnegieLearningWeb/educational-experiment-service#51]
In the CLI use case, certain parts of the system use opaque identifiers for users' work, which are not the same as user IDs.  In order to support this, we'd like UpGrade to support a notion of alternative user IDs.  This works in two steps:

### Establishing Alternate IDs

A new API called `setAltUserIds()` should be added.  This API takes the normal user ID as one parameter, and a list of alternate IDs for that user as a second parameter.  When UpGrade receives this API call, it appends the given list of alternate IDs to any alt IDs from previous invocations of this call and stores them.

### Using Alternate IDs

Any API call supported by the [client library](https://github.com/CarnegieLearningWeb/educational-experiment-service-client-libs) should transparently accept either the normal user ID or an alternate user ID.  If an alternate user ID is passed in by the client, the service should silently translate it into the associated normal user ID and continue on with the rest of the processing as normal.

An API to retrieve all alternate IDs for a given normal user ID is not necessary for our use case.

### Alternate IDs in the GUI

I don't believe it's necessary to expose alternate IDs in the [UpGrade client UI](https://github.com/CarnegieLearningWeb/educational-experiment-client/).  At least in the CLI use case, they are not meaningful to users of UpGrade; they are a only a behind-the-scenes mechanism for making it easier for federated systems like CLI to use the UpGrade client library APIs.

**Comment by VivekFitkariwala** [comment]
Some limitations here to consider

`AltUserId` can never act as a **normal userId**? Means an userId will be either **normal** userId or an **alternate**? And **alternate** userId will be associated with only one **normal** userId? Should we consider delete options for an **alternate** userId if it is associated incorrectly with **normal** userId?

**Comment by jerith666** [comment]
> AltUserId can never act as a normal userId? Means an userId will be either normal userId or an alternate?

Yes, a userId is either a normal or an alternate, never both.

But, an alternate ID _always_ acts as a normal id, in the sense that a user of the client library is allowed to substitute an alternate id _anywhere_ that a normal id would be expected, and the server will automatically dereference it.  (I think that includes the ability to define alternate IDs for an alternate ID, and have them be transitively associated back to the "root" normal ID.  Though we don't need that for our use case, so it's fine to defer that if you want.)

> And alternate userId will be associated with only one normal userId?

Yes, it would be an error to try to associated the same alternate user ID with more than one normal ID.  The server can respond with `HTTP 400 Bad Request` if the client tries to do that.

> Should we consider delete options for an alternate userId if it is associated incorrectly with normal userId?

It wouldn't hurt to have this ability, but because of the way we construct our alternate IDs, I don't anticipate it being needed in our use case.

**Comment by VivekFitkariwala** [comment]
Here is the implementation #52
