### ISSUE TITLE
Add support for using environment.json to override context and adminUsers

### ISSUE THREAD

**Issue by mfugate1** [CarnegieLearningWeb/educational-experiment-service#68]
Currently adminUsers and context are set in packages/Upgrade/src/config.json. It would be nice if I could specify those values in the environment.json file I create at deployment time so that I can avoid having to modify config.json as part of the deployment process.

**Comment by VivekFitkariwala** [comment]
We can't pass object in Environment variables as limitation from AWS end
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environments-cfg-softwaresettings.html
Only these characters are allowed _ . : / + \ - @

To add adminUser and context we have to use one of these symbols as delimiter but this will make the value complex. Let me know what you think

**Comment by mfugate1** [comment]
The alternative on my end would be to build docker images for each environment, and for each of them I modify config.json with our overrides before building and publishing the image. I'm not a fan of that approach since we try to keep build and deployment uncoupled. 

So I would be fine with being able to set a string value in environment.json with a delimiter that gets used after the service has been deployed. It may be ugly but it allows us to continue building a single image and then deploying it to multiple environments.

**Comment by VivekFitkariwala** [comment]
config.json depends on environment and environment variables is a better place for these variables
I have updated the terraform script with new environment variables and added sample in `tfvars.sample`. You need to update the environment before deploying new code.

Apart from this, config json also contain
```
"clientApi": {
    "secret": "carnegilearning",
    "data": {
      "APIKey": "494ae733-53cb-4c64-a24e-dab23d55eeb4"
    }
  }
```
**Secret** is JWT token secret which will be send along with client side http request
**data** is a json which you will be comparing after decrypting JWT token using the secret.
I think you are not sending JWT from the client side SDK yet. I will move this variables to the environment variables and delete config.json

**Comment by mfugate1** [comment]
It looks like you're using @ as a delimiter for ADMIN_USERS, but I don't think that'll work since the email addresses will also contain that symbol

**Comment by VivekFitkariwala** [comment]
Yup, you are correct. I have changed the delimiter.
