### ISSUE TITLE
Sporadic test case failure

### ISSUE THREAD

**Issue by mfugate1** [CarnegieLearningWeb/educational-experiment-service#79]
Can't reproduce this all the time, but here's the error in case you can think of a way to prevent it from happening.
```
 â— Integration Tests â€º Group User Count for State Change to Enrollment Complete

    expect(received).toEqual(expected) // deep equality

    Expected: ArrayContaining [ObjectContaining {"assignmentUnit": "group", "consistencyRule": "group", "name": "Test Experiment", "postExperimentRule": "continue", "state": "enrollmentComplete"}]
    Received: [{"assignmentUnit": "group", "conditions": [{"assignmentWeight": 60, "conditionCode": "ConditionB", "createdAt": 2020-09-24T11:20:53.135Z, "description": "Condition B", "id": "d2702d3c-5e04-41a7-8766-1da8a95b72ce", "name": "Condition B", "twoCharacterId": "CB", "updatedAt": 2020-09-24T11:20:53.135Z, "versionNumber": 1}, {"assignmentWeight": 40, "conditionCode": "ConditionA", "createdAt": 2020-09-24T11:20:53.135Z, "description": "Condition A", "id": "c22467b1-f0e9-4444-9517-cc03037bc079", "name": "Condition A", "twoCharacterId": "CA", "updatedAt": 2020-09-24T11:20:53.135Z, "versionNumber": 1}], "consistencyRule": "group", "context": ["home"], "createdAt": 2020-09-24T11:22:18.537Z, "description": "Test Experiment Description", "endDate": null, "endOn": null, "enrollmentCompleteCondition": {"groupCount": 2, "userCount": 2}, "group": "teacher", "id": "be3ae74f-370a-4015-93f3-7761d16f8b17", "name": "Test Experiment", "partitions": [{"createdAt": 2020-09-24T11:20:53.135Z, "description": "Partition on Workspace 1", "expId": "W1", "expPoint": "CurriculumSequence", "id": "W1_CurriculumSequence", "twoCharacterId": "W1", "updatedAt": 2020-09-24T11:20:53.135Z, "versionNumber": 1}, {"createdAt": 2020-09-24T11:20:53.135Z, "description": "Partition on Workspace 2", "expId": "W2", "expPoint": "CurriculumSequence", "id": "W2_CurriculumSequence", "twoCharacterId": "W2", "updatedAt": 2020-09-24T11:20:53.135Z, "versionNumber": 1}, {"createdAt": 2020-09-24T11:20:53.135Z, "description": "No Partition", "expId": null, "expPoint": "CurriculumSequence", "id": "CurriculumSequence", "twoCharacterId": "NP", "updatedAt": 2020-09-24T11:20:53.135Z, "versionNumber": 1}], "postExperimentRule": "continue", "queries": [], "revertTo": null, "startDate": 2020-09-24T11:22:18.613Z, "startOn": null, "state": "enrolling", "tags": [], "updatedAt": 2020-09-24T11:22:18.614Z, "versionNumber": 2}]

      140 |       expect.objectContaining({
      141 |         name: experimentObject.name,
    > 142 |         state: EXPERIMENT_STATE.ENROLLING,
          |                             ^
      143 |         postExperimentRule: experimentObject.postExperimentRule,
      144 |         assignmentUnit: experimentObject.assignmentUnit,
      145 |         consistencyRule: experimentObject.consistencyRule,

      at Object.<anonymous> (test/integration/Experiment/conditionalStateChange/GroupUserCount.ts:142:29)
      at fulfilled (node_modules/tslib/tslib.js:112:62)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 55 passed, 56 total
```

**Comment by tanmayjain3** [comment]
Hi @mfugate1 I tried reproducing it locally but this test case seems to pass everytime

**Comment by tanmayjain3** [comment]
In the post_experiment_rule we have renamed revert to assign. Added "assign" in education_experiment_types and renamed POST_EXPERIMENT_RULE.REVERT to POST_EXPERIMENT_RULE.ASSIGN where ever it is used in backend. Also added migration changes in table as it will expect "assign" in experiment table.

**Comment by jerith666** [comment]
I was asked in the weekly status meeting if I could provide some help here.  I tried to replicate by running `npm run test:upgrade` in the root directory at commit f8c498f189a32c340677db04bcde344838689de1, but it failed because it couldn't execute `nps`.  I tried some `yarn install` commands to get the missing dependencies, but there doesn't seem to be an end in sight after three or four of them.

Sorry, I'm not a typescript developer ... :-/

@mfugate1, maybe you can tell us what this is blocking, or if you know what commit it first happened at, or anything like that?

**Comment by mfugate1** [comment]
It's not blocking anything. I can only recall seeing this once or twice since I set up the automation to build this stuff with Jenkins months ago, so I figured I'd document it here in case it happens again.

**Comment by tanmayjain3** [comment]
Hi @mfugate1 , can you confirm the change we merged in this commit is working as aspected. You can check it by creating new experiment and in POST_EXPERIMENT_RULE dialog select ASSIGN and any of the conditions. 

Also can we go ahead and merge other PR's ? I hope the pipelines won't fail due to the above test case failure.

**Comment by mfugate1** [comment]
I can confirm that the build and deployment process on our side is working as expected, and this failure is not reproducible. All test cases are passing now. Closing this issue.
