### ISSUE TITLE
Metrics should be universal, not (only) per-user

### ISSUE THREAD

**Issue by msandbothe** [CarnegieLearningWeb/educational-experiment-service#87]
Currently setting the metrics schema is tied to a user, this means that if I or a service sends over the metrics metadata schema, other users on the platform do not gain access to those metrics when they should.

There may be two levels of metrics (universal and per-user), but universal seems like the main use case.

**Comment by nirmalpatel** [comment]
We tried adding a metric from UpGrade UI from JD's account, and it appeared in my account in the UI. Can you try that with two accounts on your side and see what happens?

**Comment by msandbothe** [comment]
Great! We have universal metrics. We probably want to make that more clear.

**Comment by SritterCL** [comment]
I'm not sure what it means to add a metric from someone's account.

The metadata coming from the educational app (MATHia) specifies the possible metrics. A user can then pick one of those metrics to be monitored by a specific experiment (and, if multiple users have access to that experiment, any of them can add or delete metrics - but the set of metrics belong to the app, and the monitored metrics belong the experiment.

Am I missing something?

**Comment by nirmalpatel** [comment]
@SritterCL you are right. Let me just recap:

Metric definition metadata are universal and they belong to the app. You can add them from the UI or through an API (Vivek made a UI to add/remove metric definitions and it appears under the profile tab). This is what Mike is asking about in this issue. See the screenshot below for the UI:

![image](https://user-images.githubusercontent.com/830400/98430945-56b9b280-20d7-11eb-953e-6d6ee35d05ea.png)

Monitored Metrics belong to individual experiments as you describe.
