### ISSUE TITLE
Experiment is lost when I hit return

### ISSUE THREAD

**Issue by SritterCL** [CarnegieLearningWeb/educational-experiment-service#90]
I was entering an experiment and was on panel 2 (entering the conditions). I typed "first" for the condition name and then hit return. The "add experiment" dialog disappeared, and none of the data from the first panel was saved.

I was expecting "return" to go to the next input field, not dismiss the dialog.

**Comment by JD2455** [comment]
@SritterCL As per the comment, I've updated code which will not disappear the "add experiment" dialog by hitting return key or esc key. For going to the next input field by hitting return key, tab key is exactly doing the same in every form of "add experiment" dialog.
